In [2]:
import numpy as np 
import matplotlib.pyplot as plt
from scipy import ndimage 
from keras.datasets import mnist 
from tqdm import tqdm_notebook #used for progress bar - how far through training we are



/home/leadsoc/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
/home/leadsoc/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/leadsoc/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/leadsoc/anaconda3/lib/python3.6/site-p

In [12]:

def process_input(X,Y):
    X = np.reshape(X,(X.shape[0], 28,28,1))
    X= X/255 #normalise input features 
    
    #print('initial', Y)
    Y = np.eye(10)[Y.reshape(-1)].T #Y.reshape(-1) flattens the input to a 1D array
    #in general np.eye(num_classes)[array].T will take a 1D array with m training examples, and 
    #one-hot encode it into a (num_classes,m) matrix
    #print('after reshape', Y)
    idx = np.random.permutation(np.arange(X.shape[0])) #shuffle indices
    
    X = X[idx]
    Y = Y[:,idx]
    
    #print('after one hot')
    
    return X,Y


# Y = np.array([0,3,2,0,1,2,3])
Y = np.eye(5)[Y.reshape(-1)].T
idx = np.random.permutation(len(Y)) #shuffle indices
    
print(Y)
print(idx)
print(Y[:,idx])



# We can split the training set, so 10,000 of these examples are kept aside for our validation set.



In [14]:


(x_train_dev, y_train_dev), (x_test, y_test) = mnist.load_data()

x_train_dev, y_train_dev = process_input(x_train_dev, y_train_dev)

x_train, y_train = x_train_dev[:-10000], y_train_dev[:,:-10000]
x_dev, y_dev = x_train_dev[-10000:], y_train_dev[:,-10000:]

x_test , y_test = process_input(x_test , y_test)


initial [5 0 4 ... 5 6 8]
after reshape [[0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]]
after one hot
initial [7 2 1 ... 4 5 6]
after reshape [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
after one hot


# Convolution Forward, 
Currently only pad==same is supported

In [16]:


def conv_forward(x, w, bias, stride=1, pad='same'):
    
    # x - is input
    # w is weights
    # b is bias
    
    
    # extract dimensions
    (row, column, filters_x)  = x.shape()
    (width, height, filters_w) = w.shape()

    
    if (filters_x == filters_w):
        if pad == 'same':
           pd =  int(width/2)
    else:
        print("Exception ,filter size does not match", filters_x, filters_w)
        
    row_out = row+pad
    col_out = column+pad
    f_w = filter_out = filters_w
    
    print("row, column, pd, row_out", row, column, pd, row_out)
    
    y = np.zeros( row, column, filters)
    
    for r in range(0,row,stride):
        
        for c in range(0, column,stride):
            
            for f in range(filters_w):
                
                x_slice = x(r:r+f_w, c:c+f_w,f)
                
                y[r:r+f_w, c:c+f_w,f] = sum(x_slice*w[:,:,f])
        
        
    return y
    
    
    
    

SyntaxError: invalid syntax (<ipython-input-16-3a858d6174f4>, line 15)